apiVersion: authorization.cci.vmware.com/v1alpha1
kind: ProjectRoleBinding
metadata:
  # name must match the subject kind and name
  name: cci:user:yourdomain.com:jsmith
  namespace: cci
subjects:
  - kind: User  # User / Group
    name: "jsmith@yourdomain.com"  # UPN your name here
roleRef:
  apiGroup: authorization.cci.vmware.com
  kind: ProjectRole
  name: admin # admin / edit / view